### ISSUE TITLE
pillar.example seems wrong

### ISSUE THREAD

**Issue by GabLeRoux** [taion809/oh-my-zsh-formula#1]
```
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["Rendering SLS 'base:oh-my-zsh' failed: Jinja variable 'list object' has no attribute 'name'"]}
```

The part about users which looks like this:

```
oh-my-zsh:
  user:
    - name: vagrant
    - group: vagrant
    - home: /home/vagrant
```

is being used like this in the state instead:

```
oh-my-zsh:
  user:
    name: vagrant
    group: vagrant
    home: /home/vagrant
```

Which is wrong. Looks like there's a missing loop ;)

Looks fixed in upstream https://github.com/leifcr/oh-my-zsh-formula.

On upstream, I couldn't manage to find what's the syntax exactly. Sounds like it would look something like:

```
oh-my-zsh:
  users:
    - username: vagrant
      group: vagrant
      home: /home/vagrant
```

But I'm getting 

```
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["Rendering SLS 'base:oh-my-zsh' failed: Jin
ja variable 'list object' has no attribute 'items'"]}
```

**Comment by GabLeRoux** [comment]
Found the solution:

```
oh-my-zsh:
  users:
    vagrant:
      username: vagrant
      group: vagrant
      home: /home/vagrant
```

Using forked repo.
